sudo: true
# After a few years
dist: xenial
arch: ppc64le
language: c++
env:
  - DEBUG=1
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
install:
  - sudo apt-get update
    #  - sudo do-release-upgrade -p -f DistUpgradeViewNonInteractive
  - sudo apt-get --yes install systemd cmake catch libsystemd-dev libncurses5-dev gcc g++ build-essential ssh
script:
  - mkdir build; cd build; cmake ../; make; sudo make Test

